### ISSUE TITLE
VS2017 access violation error

### ISSUE THREAD

**Issue by gurkanctn** [OneLoneCoder/videos#15]
Using the latest version of the Header file,
I've tried the code given in the video : (Absolute Beginners Guide To "olcConsoleGameEngine.h")

Here's the error message I get at runtime:

`Exception thrown: write access violation.
this->m_bufScreen was 0x1110112.`

The line that gives the error is the last one here:
```
virtual void Draw(int x, int y, short c = 0x2588, short col = `0x000F)

	{
		if (x >= 0 && x < m_nScreenWidth && y >= 0 && y < m_nScreenHeight)
		{
			m_bufScreen[y * m_nScreenWidth + x].Char.UnicodeChar = c;

```
Note: I have already changed the Project settings to UNICODE.

**Comment by gurkanctn** [comment]
After checking through Google, I've found the reason of the error..
[Link Here](https://br-new.com/online/path-planning-a-a-star-icZj67PTFhc.html)

and the reason is the size of the screen. 160x100 did not work, 40 x 40 did work.
Here's the working line:
`	demo.ConstructConsole(40, 40, 8, 8);`

**Comment by OneLoneCoder** [comment]
Yes, the console needs to fit on the primary display of the computer, so the resolution multiplied by the character size must remain less than your desktop resolution. Rather than lowering the resolution, you can also lower the character size, which is visually a little more appealing

**Comment by UncleBob2** [comment]
> After checking through Google, I've found the reason of the error..
> [Link Here](https://br-new.com/online/path-planning-a-a-star-icZj67PTFhc.html)
> 
> and the reason is the size of the screen. 160x100 did not work, 40 x 40 did work.
> Here's the working line:
> ` demo.ConstructConsole(40, 40, 8, 8);`

I am unable to view the link. Can you tell us how to solve this problem again as I am unable to find the size of the screen "160x100 did not work, 40 x 40 did work."

**Comment by UncleBob2** [comment]
I thinking that I got it working now:



int main()
{
	OneLoneCoder_PathFinding game;
	game.ConstructConsole(160, 160, 5,5);
	game.Start();
	return 0;
}

**Comment by gurkanctn** [comment]
> > After checking through Google, I've found the reason of the error..
> > [Link Here](https://br-new.com/online/path-planning-a-a-star-icZj67PTFhc.html)
> > and the reason is the size of the screen. 160x100 did not work, 40 x 40 did work.
> > Here's the working line:
> > ` demo.ConstructConsole(40, 40, 8, 8);`
> 
> I am unable to view the link. Can you tell us how to solve this problem again as I am unable to find the size of the screen "160x100 did not work, 40 x 40 did work."

I couldn't access the link either. However, the solution to my problem was the construct line of the application:
The engine constructs the screen by the line:
`demo.ConstructConsole(Width, Height, size_of_pixel_x, size_of_pixel_y);`

**Comment by UncleBob2** [comment]
> > > After checking through Google, I've found the reason of the error..
> > > [Link Here](https://br-new.com/online/path-planning-a-a-star-icZj67PTFhc.html)
> > > and the reason is the size of the screen. 160x100 did not work, 40 x 40 did work.
> > > Here's the working line:
> > > ` demo.ConstructConsole(40, 40, 8, 8);`
> > 
> > 
> > I am unable to view the link. Can you tell us how to solve this problem again as I am unable to find the size of the screen "160x100 did not work, 40 x 40 did work."
> 
> I couldn't access the link either. However, the solution to my problem was the construct line of the application:
> The engine constructs the screen by the line:
> `demo.ConstructConsole(Width, Height, size_of_pixel_x, size_of_pixel_y);`

I believe OneLoneCoder has changed the source code from demo.ConstructConsole to game.ConstructConsole; hence, I was unable to find demo.ConstructConsole before. Now everything make sense. Many thanks.
