### ISSUE TITLE
Unable to use Command Prompt Console Game Engine. Access violation reading location 0x00000000

### ISSUE THREAD

**Issue by erikmartinessanches** [OneLoneCoder/videos#24]
Following your [video](https://youtu.be/cWc0hgYwZyc), I set up a C++ Console project in VS2017 version 15..9.5. I get this error when debugging:

`Exception thrown at 0x770B0FAC (KernelBase.dll) in CommandPromptConsoleGameEngineIntro.exe: 0xC0000005: Access violation reading location 0x00000000.`

[My repository](https://github.com/erikmartinessanches/OLCvids).

**Comment by OneLoneCoder** [comment]
This could be because you are creating a console that is too big for your screen. Looking at your repo, your console will be 960x800 pixels minimum. Windows requires consoles fit on the primary display.

**Comment by erikmartinessanches** [comment]
Thanks, that was it!
