### ISSUE TITLE
Library unusuable in Linux

### ISSUE THREAD

**Issue by DanteFalzone0** [OneLoneCoder/videos#29]
Tried using your library on my Linux machine and it fell flat because of the "windows.h" library. I do not own a Windows machine and don't intend to get one.

**Comment by OneLoneCoder** [comment]
Correct, it is windows based. On linux, use olcConsoleGameEngineSDL.h

**Comment by OneLoneCoder** [comment]
or for a more conventional library that is conceptually identical, olcPixelGameEngine is genuinely cross platform
