### ISSUE TITLE
Exception Thrown During Debug

### ISSUE THREAD

**Issue by HiCharity** [OneLoneCoder/videos#33]
Exception thrown: write access violation.
this->**m_bufScreen** was 0x1110112. occurred

^^I assume something is wrong with the parameters of drawing the screen but I do not know. Any help is appreciated.

**Comment by rmcuenen** [comment]
You're trying to construct a console that is too large for your screen. Try to lower the number of rows/columns or the scaling factor

**Comment by OneLoneCoder** [comment]
This is correct.

**Comment by FilipLitwora** [comment]
I had the same problem, lowering number of rows/cols helped. That's weird because I copied the values from olc's [https://www.youtube.com/watch?v=cWc0hgYwZyc](video)...

**Comment by rmcuenen** [comment]
> I had the same problem, lowering number of rows/cols helped. That's weird because I copied the values from olc's [video](https://www.youtube.com/watch?v=cWc0hgYwZyc) (3:48)...

I guess it depends on your own screen resolution. With: `game.ContructConsole(160, 100, 8, 8)` you're trying to construct a 1280x800 console, but I don't think that's including the window borders and decorations. The task bar will also take up space on your screen, so there might not be enough real estate left to create the requested console.
