### ISSUE TITLE
olcConsoleGameEngine.h for linux

### ISSUE THREAD

**Issue by khojiakbar17** [OneLoneCoder/videos#34]
As we know, there is no windows.h library in linux. So is there a port of olcConsoleGameEngine.h for linux?

**Comment by OneLoneCoder** [comment]
There is, in this repo there is olcConsoleGameEngineSDL.h, but I would urge people to use olcPixelGameEngine which is cross platform, has the same interface as ConsoleGameEngine, but is maintained more frequently and is significantly more powerful.
