### ISSUE TITLE
Jario-sprites to png

### ISSUE THREAD

**Issue by krusator** [OneLoneCoder/videos#41]
Hi there,

I'm trying to convert the platform tile of jario from the consoleGameEngine to the pixelGameEngine.
And as I learned today through the SHMUP video the _DrawSprite_ function of the pixelGameEngine can only handle png and not spr files.

Question: is there a way to convert the jario sprites into png files?

Cheers
Sascha

**Comment by SweFjorod** [comment]
I made a program for just that issue, it's here on github : https://github.com/SweFjorod/MapEditor

**Comment by krusator** [comment]
Thx, I'll give it a try.
