### ISSUE TITLE
solve the sprite overlay issue in the commandlineFPS part2

### ISSUE THREAD

**Issue by kingatgi** [OneLoneCoder/videos#7]
to solve the sprite list store order causing  the sprite render overlay issue just simply change the 1D depthBuffer to a 2D depth buffer(now the column depth buffer create in the raytracing of the wall should change to adjust to the buffer size change. 
And also at the sprite object render section just change the depth buffer column check to pixel by pixel.that's it.

**Comment by OneLoneCoder** [comment]
lol, i know, and I have, but the video got too long... Part #3 earlier this year will address a couple of issues. One is the fish eye effect. I'm going to merge the fps with A* and maze generation videos to actually make a game out of it.
