### ISSUE TITLE
3d console game engine does not display properly in Windows Terminal

### ISSUE THREAD

**Issue by SheepReaper** [OneLoneCoder/videos#72]
In Windows 11 (possibly 10, as well) you can set Windows terminal as the default terminal emulator as opposed to the windows console host. This also applies when debugging in VS. In its current state, when used in an application like the 3d game engine videos, the application appears to run, but the font size does not appear to be respected. I can change some of the behavior by using virtual terminal mode as M$ recommends instead and using the alternate buffer via escape sequence, but am now having issues with setting the buffer dimensions. Namely the maximum window sizes are not the same as when running under console host. (Height becomes 2, and the width seems fixed at 128.)

**Comment by SheepReaper** [comment]
Closing my own issue. It seems that Font APIs and buffer size changes are not and will not be supported. Also, window resizing is likewise currently not supported. ref: https://github.com/microsoft/terminal/issues/6832#issuecomment-655684556
So for others stumbling on this, the 3d console game engine will likely not ever run under windows terminal but will work just fine in console host, so change your default terminal application setting to console host while working with this project.

**Comment by KhalidAlnujaidi** [comment]
wow thank you very much!

**Comment by KhalidAlnujaidi** [comment]
Step-by-Step Guide to Run in Console Host
Open Visual Studio:
Start Visual Studio and open your project.

Change Default Terminal Application:

Windows Settings:
Press Win + X and select Settings.
Go to Privacy & security -> For developers.
Scroll down to the Terminal section.
Under Default terminal application, select Windows Console Host.
Verify Terminal Settings in Visual Studio:
Ensure that Visual Studio is configured to use the default terminal application for debugging:

In Visual Studio, open your project.
Go to the Project menu and select [ProjectName] Properties.
Navigate to the Debug tab.
Ensure that Command is set to the path of your executable, and check the Working Directory is set correctly.
Ensure that Launch is set to Project.
Configure Project for Console Output:
Make sure your project is set up to use the Console for output:

Right-click on your project in the Solution Explorer.
Select Properties.
Under Configuration Properties, go to Linker -> System.
Ensure Subsystem is set to Console (/SUBSYSTEM:CONSOLE).
Run Your Project:

Press F5 or click the Start Debugging button in Visual Studio to run your project.
Your application should now open in the Console Host.
